syntax = "proto3";
package common;

option go_package = "gitlab.com/thorchain/thornode/v3/common";
option (gogoproto.goproto_stringer_all) = false;
option (gogoproto.stringer_all)         = false;
option (gogoproto.goproto_getters_all)  = false;

import "amino/amino.proto";
import "gogoproto/gogo.proto";

message Asset {
    string chain = 1 [(gogoproto.casttype) = "Chain"];
    string symbol = 2 [(gogoproto.casttype) = "Symbol"];
    string ticker = 3 [(gogoproto.casttype) = "Ticker"];
    bool synth = 4;
    bool trade = 5;
    bool secured = 6;
}

message Coin {
    Asset asset = 1 [(gogoproto.jsontag) = "asset", (gogoproto.nullable) = false, (gogoproto.customtype) = "Asset", (amino.encoding) = "asset"];
    string amount = 2 [(gogoproto.jsontag) = "amount", (gogoproto.customtype) = "cosmossdk.io/math.Uint", (gogoproto.nullable) = false];
    int64 decimals = 3;
}